# default 설정
spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    generate-ddl: true
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://localhost:3306/billybangdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: pda_billybang_admin
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://localhost:3306/billybangdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: pda_billybang_admin




