server:
  port: 3000

spring:
  application:
    name: user-service
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create # TODO : test ????? ? ?
  datasource:
    url: jdbc:mariadb://localhost:3306/billybangdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: pda_billybang_admin
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

